export enum ErrorCode {
  /**
   * 메모 폴더 에러
   */
  INVALID_MEMO_FOLDER_NAME = 'MF0000',
  DUPLICATE_MEMO_FOLDER_NAME = 'MF0001',
  MEMO_FOLDER_NOT_FOUND = 'MF0002',

  /**
   * 메모 에러
   */
  DUPLICATE_MEMO_NAME = 'M0000',
  MEMO_NOT_FOUND = 'M0001',
  INVALID_MEMO_NAME = 'M0002',
  INVALID_MEMO_IMAGE = 'M0003',

  /**
   * 인증 에러
   */
  SIGN_IN_FAILED = 'A0000',
  NOT_SUPPORTED_OAUTH_PROVIDER = 'A0001',
  INVALID_JWT = 'A0002',
  JWT_EXPIRED = 'A0003',

  /**
   * 회원 에러
   */
  MEMBER_NOT_FOUND = 'MB0000',
}
